### ISSUE TITLE
Zone not being updated

### ISSUE THREAD

**Issue by TaiSHiNet** [cloudflare/Cloudflare-CPanel#161]
Hi,

When I enable CF (CNAME) for a domain, the following happens:
`www (former CNAME) record gets pointed to www.domain.com.cdn.cloudflare.net.`
`domain.com. stays the same (A record to IP)`
`cloudflare-resolve-to is created doing a CNAME point to domain.com. `

I click (back and forth) on the plugin panel to enable/disable, and the zone remains unchanged afterwards.
I solved it (manually) by editing:
`domain.com. CNAME domain.com.cdn.cloudflare.net.`
`www CNAME domain.com.cdn.cloudflare.net.` (no www in front, it worked for me)
`cloudflare-resolve-to A server.ip.address`

Any pointers at what could be wrong?

**Comment by thellimist** [comment]
The plugin does the intended CName change which is for subdomains. For more information you can read [here](https://support.cloudflare.com/hc/en-us/articles/200168706-How-do-I-do-CNAME-setup-).

To keep it short, some DNS authorities support CName flattening meaning for those authorities it is possible to do non-subdomain CNames. Since the plugin is a generic software, it only does the officially supported actions which is supporting CName while using subdomains (as provided in the link).

**Comment by TaiSHiNet** [comment]
Awesome, I'll switch to full zone provisioning then.
Closing the ticket as it's a non-issue
