### ISSUE TITLE
6.0 install problem

### ISSUE THREAD

**Issue by chispaa** [cloudflare/CloudFlare-CPanel#81]
Hi,

When installing the 6.0 plugin on cPanel 56, I get this output:

```
Starting CloudFlare CPanel Installation...
Downloading and unpacking latest version v6.0.0...
info [install_plugin] Installing to paper_lantern
info [install_plugin] Installing cloudflare in feature manager ...
info [install_plugin] Done
info [install_plugin] Running sprite_generator
Plugin installed ok
Cleaning up

# cat /usr/local/cpanel/etc/cloudflare.json
cat: /usr/local/cpanel/etc/cloudflare.json: No such file or directory
```

Is the plugin compatible with this version?. Mod_cloudflare is not available in EA3.

Thanks!.

**Comment by jwineman** [comment]
Hi,

Two things:

We no longer use cloudflare.json in version 6.0 of the plugin.

mod_cloudflare was removed from the installer because its not compatible with EasyApache4 and we were getting lot of support tickets.  We decided to remove it until we have a chance to fix it.  In the mean time you should be able to install it on EasyApache3 with

`bash <(curl -s https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/EasyApache/installer.sh)`
