### ISSUE TITLE
Auto update does not work < 6.0.2

### ISSUE THREAD

**Issue by pinhao** [cloudflare/CloudFlare-CPanel#92]
Shouldn't the output of curl be piped into bash?

https://github.com/cloudflare/CloudFlare-CPanel/blob/master/cloudflare_update.sh#L42-L43

**Comment by arthurcf** [comment]
The script works correctly as designed, there is no reason to pipe the shell script directly from the Internet to bash. Not doing so is also slightly more secure, since at least disk write permissions are checked when the file is downloaded. Using a pipe would skip that check. Also please note that the download is via HTTPS to prevent man-in-the middle issues.
